### PR TITLE
[1.4.x] Added graceful shutdown function to consumers

### PR DESCRIPTION
**Pull request by thetomcake**
We were looking at adding graceful shutdown to the library as we use it inside k8s and we are currently unable to stop kafka consumers without killing the container.

Hopefully this should help for anyone in a similar situation.

### CODE REVIEW

**Comment by mateusjunges** [comment]
Good morning @thetomcake 
Just a question: if i run my consumers via laravel commands through supervisor, how can i get the consumer instance to call the `stopConsume` method? Am i missing something?

**Comment by mateusjunges** [comment]
Now i get it from the docs. You install a signal handler before start consuming messages. Good!

**Review by mateusjunges — APPROVED** [review]

**Comment by mateusjunges** [comment]
Thank you again @thetomcake!

**Comment by thetomcake** [comment]
> Thank you again @thetomcake!

You're welcome :-)

**Pull request merged**
