### PR TITLE
Fixes #120

### LINKED ISSUE #120: [BUG] stopAfterLastMessage not working
I'm calling the method stopAfterLastMessage() on the consumer building but the consumption don't stop.

I'm on ubuntu 22.04, running php 8.1 with rdkafka 6.0.3, laravel-kafka:1.8.1.

I check the code and in line 349 we have this:
`        if ($this->config->shouldStopAfterLastMessage() && RD_KAFKA_RESP_ERR__PARTITION_EOF === $message->err) {
`
RD_KAFKA_RESP_ERR__PARTITION_EOF equals -191 but $message->err is returning -185, i try to send a pull request but i get access denied, so i am sending the code that would be like this:

```
    private const CONSUMER_STOP_ERRORS = [
        RD_KAFKA_RESP_ERR__PARTITION_EOF,
        RD_KAFKA_RESP_ERR__TIMED_OUT
    ];
    
   ....
   
    if ($this->config->shouldStopAfterLastMessage() && in_array($message->err, self::CONSUMER_STOP_ERRORS)) {
        $this->stopConsume();
    }
```

### PR DESCRIPTION
**Pull request by ThomasEnssner**

### CODE REVIEW

**Comment by mateusjunges** [comment]
Hi @ThomasEnssner, is it possible to add tests?

**Comment by ThomasEnssner** [comment]
I'm in holidays from tomorrow until 22th of August. Won't get it done before.

**Comment by mateusjunges** [comment]
Ok. I'll work on it then

**Comment by mateusjunges** [comment]
I'm closing this one since this is not the correct fix. Thanks!

**Pull request closed without merging**
